using UnityEngine;

namespace SoulFlameAsset
{
    // Presentation only. The host remains enabled at zero HP so Reset can relight it.
    public sealed class SoulFlameVisual : MonoBehaviour
    {
        [SerializeField] private Transform visualRoot;
        [SerializeField] private ParticleSystem core;
        [SerializeField] private ParticleSystem sparks;
        [SerializeField] private ParticleSystem hitBurst;
        [SerializeField] private Light glow;
        [SerializeField] private Color flameColor = new Color(0.08f, 0.8f, 1f, 1f);
        [SerializeField, Min(0.05f)] private float fadeSeconds = 0.45f;
        [SerializeField, Min(0f)] private float lightIntensity = 0.7f;
        private Renderer[] particleRenderers;
        private MaterialPropertyBlock properties;
        private Vector3 originalScale;
        private int lastHP = -1, lastMax = -1;
        private float strength = 1f, target = 1f, hitTime;
        private bool initialized, cleared;
        private static readonly int Tint = Shader.PropertyToID("_Tint");
        private static readonly int Opacity = Shader.PropertyToID("_Opacity");
        public bool IsExtinguished => target <= 0f && strength <= 0.001f;

        public void Configure(Transform art, ParticleSystem mainFire, ParticleSystem embers,
            ParticleSystem impact, Light lightSource, Color color)
        {
            visualRoot = art; core = mainFire; sparks = embers;
            hitBurst = impact; glow = lightSource; flameColor = color;
        }
        private void Awake() { Initialize(); }
        private bool Initialize()
        {
            if (initialized) return true;
            if (visualRoot == null || core == null || sparks == null || hitBurst == null)
            {
                Debug.LogError("SoulFlame: use a prefab generated by Tools > Soul Flame.", this);
                enabled = false; return false;
            }
            originalScale = visualRoot.localScale;
            particleRenderers = visualRoot.GetComponentsInChildren<Renderer>(true);
            properties = new MaterialPropertyBlock(); initialized = true;
            return true;
        }
        public void SetHealth(int hp, int maximum, bool instant = false)
        {
            if (!Initialize()) return;
            maximum = Mathf.Max(1, maximum); hp = Mathf.Clamp(hp, 0, maximum);
            if (!instant && hp == lastHP && maximum == lastMax) return;
            bool hurt = lastHP >= 0 && hp < lastHP;
            lastHP = hp; lastMax = maximum;
            target = hp == 0 ? 0f : Mathf.Lerp(0.4f, 1f, (float)hp / maximum);
            if (instant)
            {
                ClearParticles(); strength = target; hitTime = 0f;
            }
            else if (hurt)
            {
                hitTime = 0.18f;
                hitBurst.Emit(hp == 0 ? 16 : 7);
            }
            if (target > 0f)
            {
                cleared = false;
                if (!core.isPlaying) core.Play(false);
                if (!sparks.isPlaying) sparks.Play(false);
            }
            Apply();
        }
        private void LateUpdate()
        {
            if (!initialized) return;
            // Keep the flame upright while its anchor follows the moving pan.
            visualRoot.rotation = Quaternion.identity;
            strength = Mathf.MoveTowards(strength, target, Time.deltaTime / Mathf.Max(0.05f, fadeSeconds));
            hitTime = Mathf.Max(0f, hitTime - Time.deltaTime);
            Apply();
        }
        private void Apply()
        {
            bool alive = strength > 0.001f;
            float flicker = 0.94f + 0.06f * Mathf.Sin(Time.time * 11f + transform.position.x * 7f);
            if (lastHP > 0 && lastHP <= Mathf.Max(1, lastMax / 3))
                flicker *= 0.85f + 0.15f * Mathf.Sin(Time.time * 19f);
            float hitScale = hitTime > 0f ? 0.78f : 1f;
            visualRoot.localScale = originalScale * Mathf.Max(0.001f, strength * flicker * hitScale);
            properties.SetColor(Tint, flameColor);
            properties.SetFloat(Opacity, alive ? Mathf.Clamp01(strength * 1.4f) : 0f);
            foreach (var renderer in particleRenderers) renderer.SetPropertyBlock(properties);
            var emission = core.emission; emission.rateOverTime = alive ? 28f * strength : 0f;
            emission = sparks.emission; emission.rateOverTime = alive ? 7f * strength : 0f;
            if (glow != null)
            {
                glow.color = flameColor; glow.intensity = lightIntensity * strength * flicker;
                glow.enabled = alive;
            }
            if (!alive && !cleared) { ClearParticles(); cleared = true; }
        }
        private void ClearParticles()
        {
            core.Stop(false, ParticleSystemStopBehavior.StopEmittingAndClear);
            sparks.Stop(false, ParticleSystemStopBehavior.StopEmittingAndClear);
            hitBurst.Stop(false, ParticleSystemStopBehavior.StopEmittingAndClear);
        }
        private void OnDisable()
        {
            if (!initialized) return;
            ClearParticles(); if (glow != null) glow.enabled = false;
            // Permit the presenter's next sync to restore an independently re-enabled visual.
            lastHP = lastMax = -1;
        }
    }
}
